/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "th-surface": "rgb(var(--color-surface) / <alpha-value>)",
        "th-surface-alt": "rgb(var(--color-surface-alt) / <alpha-value>)",
        "th-surface-dark": "rgb(var(--color-surface-dark) / <alpha-value>)",
        "th-text": "rgb(var(--color-text) / <alpha-value>)",
        "th-text-muted": "rgb(var(--color-text-muted) / <alpha-value>)",
        "th-text-hover": "rgb(var(--color-text-hover) / <alpha-value>)",
        "th-border": "rgb(var(--color-border) / <alpha-value>)",
        "th-border-medium": "rgb(var(--color-border-medium) / <alpha-value>)",
        "th-border-strong": "rgb(var(--color-border-strong) / <alpha-value>)",
        "th-marker-bg": "rgb(var(--color-marker-bg) / <alpha-value>)",
        "th-accent": "rgb(var(--color-accent) / <alpha-value>)",
        "th-accent-light": "rgb(var(--color-accent-light) / <alpha-value>)",
        "th-hover-bg": "rgb(var(--color-hover-bg) / <alpha-value>)",
        "th-now-line": "rgb(var(--color-now-line) / <alpha-value>)",
        "th-ref-line": "rgb(var(--color-ref-line) / <alpha-value>)",
        "th-hover-line": "rgb(var(--color-hover-line) / <alpha-value>)",
        "th-section-bg": "rgb(var(--color-section-bg) / <alpha-value>)",
        "th-section-bg-deep": "rgb(var(--color-section-bg-deep) / <alpha-value>)",
        "th-section-border": "rgb(var(--color-section-border) / <alpha-value>)",
        "th-event-detail-bg": "rgb(var(--color-event-detail-bg) / <alpha-value>)",
        "th-bar-empty": "rgb(var(--color-bar-empty) / <alpha-value>)",
        "th-bar-border": "rgb(var(--color-bar-border) / <alpha-value>)",
        "th-progress-bar": "rgb(var(--color-progress-bar) / <alpha-value>)",
      },
    },
  },
  plugins: [],
  darkMode: "class",
};
